---
- hosts: localhost
  vars_files:
    - vars/all_vars.yml

  tasks:
    - name: define corp name
      set_fact:
        ids: "{{ all_users.corp }}"
        resolv_domain: ".corp.domain"
      tags: corp
    
    - name: include repeated tasks
      include: all-tasks.yml
      tags: corp
